version: 2
updates:
  # npm package updates
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 10
    reviewers:
      - "neverinfamous"
    labels:
      - "dependencies"
      - "javascript"
    allow:
      - dependency-type: "all"
    rebase-strategy: "auto"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"
    pull-request-branch-name:
      separator: "/"

  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:30"
    open-pull-requests-limit: 5
    reviewers:
      - "neverinfamous"
    labels:
      - "ci"
      - "github-actions"
    commit-message:
      prefix: "ci(actions):"
      include: "scope"
